[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Use Next.js plugin for proper Netlify integration
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  # Include font files for Arabic text support
  included_files = ["public/fonts/**/*", "netlify/functions/.fonts/**/*"]
  # Worker drain endpoint settings (60 second timeout for PDF generation)
  node_bundler = "esbuild"

# Headers for font loading
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
