[build]
  command = "pnpm build"
  publish = ".next"

[functions]
  # Include font files for Arabic text support
  included_files = ["public/fonts/**/*"]

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for font loading
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Environment variables for serverless functions
[build.environment]
  NODE_VERSION = "18"
