CREATE TABLE "pdfprompt_file" (
	"id" text PRIMARY KEY NOT NULL,
	"jobId" text,
	"path" text,
	"mimeType" varchar(128) DEFAULT 'application/pdf',
	"size" integer DEFAULT 0,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pdfprompt_job" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text,
	"prompt" text,
	"status" varchar(32) DEFAULT 'queued' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"resultFileId" text,
	"errorMessage" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pdfprompt_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pdfprompt_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "pdfprompt_file" ADD CONSTRAINT "pdfprompt_file_jobId_pdfprompt_job_id_fk" FOREIGN KEY ("jobId") REFERENCES "public"."pdfprompt_job"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "pdfprompt_post" USING btree ("name");