name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Server-side environment variables
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: production
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      UPLOADTHING_TOKEN: ${{ secrets.UPLOADTHING_TOKEN }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENROUTER_BASE_URL: ${{ secrets.OPENROUTER_BASE_URL }}
      # Client-side environment variables
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      PAYPAL_PLAN_ID_CLASSIC: ${{ secrets.PAYPAL_PLAN_ID_CLASSIC }}
      PAYPAL_PLAN_ID_PROFESSIONAL: ${{ secrets.PAYPAL_PLAN_ID_PROFESSIONAL }}
      NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}
      PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
      PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
      PAYPAL_MODE: ${{ secrets.PAYPAL_MODE }}
      PAYPAL_WEBHOOK_ID: ${{ secrets.PAYPAL_WEBHOOK_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.16.1
      - run: pnpm install --frozen-lockfile
      - run: npx eslint .
      - run: pnpm run check
      - run: pnpm run build
