name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Server-side environment variables
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: production
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      UPLOADTHING_TOKEN: ${{ secrets.UPLOADTHING_TOKEN }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}
      OPENROUTER_BASE_URL: ${{ secrets.OPENROUTER_BASE_URL }}
      PDFPROMPT_WORKER_SECRET: ${{ secrets.PDFPROMPT_WORKER_SECRET }}
      PDFPROMPT_MAX_JOBS_PER_INVOCATION: ${{ secrets.PDFPROMPT_MAX_JOBS_PER_INVOCATION }}
      PDFPROMPT_MAX_MS_PER_INVOCATION: ${{ secrets.PDFPROMPT_MAX_MS_PER_INVOCATION }}
      PDFPROMPT_BATCH_SIZE: ${{ secrets.PDFPROMPT_BATCH_SIZE }}
      # Client-side environment variables
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.16.1
      - run: pnpm install --frozen-lockfile
      - run: npx eslint .
      - run: pnpm run check
      - run: pnpm run build
